# Generated by Django 5.0.8 on 2024-08-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoatividade', '0002_alter_tipoatividade_codigo'),
        ('tipoatividade', '0003_remove_tipoatividade_nome'),
    ]

    operations = [
    ]
