# Generated by Django 5.0.8 on 2024-08-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoatividade', '0006_alter_tipoatividade_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatividade',
            name='titulo',
        ),
    ]
