# Generated by Django 5.0.8 on 2024-08-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matrícula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('dataMatricula', models.DateField(help_text='Informe a Data da Matrícula do Aluno', max_length=70)),
                ('dataSaida', models.DateField(help_text='Informe a Data de Saída do Aluno', max_length=70)),
            ],
        ),
    ]
