# Generated by Django 5.0.8 on 2024-08-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_datasaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataSaida',
            field=models.DateField(blank=True, help_text='Informe a Data de Saída do Aluno', max_length=70, null=True),
        ),
    ]
