# Generated by Django 5.0.8 on 2024-08-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0002_remove_tipoatividade_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Tipo de atividade', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Informe o titulo do Tipo de Atividade', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='TipoAtividade',
        ),
    ]
