# Generated by Django 5.0.8 on 2024-08-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0003_titulo_delete_tipoatividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulo',
            old_name='titulo',
            new_name='descricao',
        ),
    ]
